In [13]:
import pandas as pd
import pickle

In [14]:
df = pd.read_pickle('../final_model_data/gamelog_exp_clust_odds.pkl')

In [15]:
df.head()

,Date,W,sos,GameType,Wp,ppg,pApg,FGp,3Pp,FTp,...,Final_v,ML_v,Team_v,p_v,VHohe_v,vegas,actual_spread,W_odds,spread,final_p
13,2013-11-30,0,1.71,season2014,0.500000,70.0,70.6,0.4688,0.3280,0.6782,...,81.0,-1210.0,colorado,0.923664,1.0,0.0,-24.0,0.0,-9.0,0.116279
14,2013-12-05,1,1.71,season2014,0.428571,68.8,72.6,0.4646,0.3372,0.6886,...,86.0,125.0,south-dakota,0.444444,1.0,1.0,8.0,1.0,-1.0,0.591837
15,2013-12-14,1,1.71,season2014,0.500000,71.2,73.0,0.4782,0.3404,0.7246,...,52.0,255.0,california-riverside,0.281690,1.0,1.0,10.0,1.0,-5.0,0.759036
16,2013-12-21,0,1.71,season2014,0.600000,73.4,71.0,0.4538,0.3400,0.7038,...,74.0,-115.0,air-force,0.534884,1.0,1.0,6.0,1.0,0.0,0.534884
17,2014-01-01,1,1.71,season2014,0.545455,76.2,70.4,0.4544,0.3566,0.7558,...,72.0,-385.0,utah-state,0.793814,1.0,0.0,1.0,1.0,-5.0,0.246914

In [5]:
df.columns

Index(['Date', 'W', 'sos', 'GameType', 'Wp', 'ppg', 'pApg', 'FGp', '3Pp',
       'FTp', 'ORBpg', 'RBpg', 'ASTpg', 'STLpg', 'BLKpg', 'TOpg', 'PFpg', 'Tm',
       'exp_factor', 'C0', 'C1', 'C2', 'F0', 'F1', 'F2', 'G0', 'G1', 'G2',
       'G3', 'OPsos', 'OPWp', 'OPppg', 'OPpApg', 'OPFGp', 'OP3Pp', 'OPFTp',
       'OPORBpg', 'OPRBpg', 'OPASTpg', 'OPSTLpg', 'OPBLKpg', 'OPTOpg',
       'OPPFpg', 'OPTm', 'OPexp_factor', 'OPC0', 'OPC1', 'OPC2', 'OPF0',
       'OPF1', 'OPF2', 'OPG0', 'OPG1', 'OPG2', 'OPG3', 'ID', 'Final', 'ML',
       'season', 'Team', 'p', 'VHohe', 'count', 'Final_v', 'ML_v', 'Team_v',
       'p_v', 'VHohe_v', 'vegas', 'actual_spread', 'W_odds', 'spread'],
      dtype='object')

In [7]:
def final_p(row):
    if row['Tm'] == row['Team']:
        row['final_p'] = row['p']
    elif row['Tm'] == row['Team_v']:
        row['final_p'] = row['p_v']
    return row

In [9]:
df = df.apply(final_p, axis=1)

In [12]:
df[['Tm', 'OPTm', 'Team', 'p', 'Team_v', 'p_v', 'final_p']].head()

,Tm,OPTm,Team,p,Team_v,p_v,final_p
13,air-force,colorado,air-force,0.116279,colorado,0.923664,0.116279
14,air-force,south-dakota,air-force,0.591837,south-dakota,0.444444,0.591837
15,air-force,california-riverside,air-force,0.759036,california-riverside,0.281690,0.759036
16,air-force,california-davis,california-davis,0.512195,air-force,0.534884,0.534884
17,air-force,utah-state,air-force,0.246914,utah-state,0.793814,0.246914