In [1]:
import pandas as pd 
import numpy as np
import pickle

In [2]:
gamelogs = pd.read_pickle('../data/gamelog_data_5_game_rolling.pkl')

In [3]:
clusters = pd.read_pickle('../data/team_clusters.pkl')

In [4]:
experience = pd.read_pickle('../data/team_experience.pkl')

In [5]:
def ID(row):
    row['ID'] = ",".join([row['Team'], str(row['Season'])])
    return row

In [17]:
# Change Tm column to Team
gamelog_cols = gamelogs.columns.tolist()
gamelog_cols = [i if i!= 'Tm' else 'Team' for i in gamelog_cols]
gamelogs.columns = gamelog_cols

In [23]:
gamelogs.head()

,Date,Opp,W,sos,GameType,Ws,Wp,ppg,pApg,FGp,...,FTp,ORBpg,RBpg,ASTpg,STLpg,BLKpg,TOpg,PFpg,Team,Season
0,2014-01-09,new-orleans,0,-4.12,season2014,2.0,0.200000,63.8,68.8,0.3938,...,0.7078,7.8,27.4,12.2,7.2,2.8,13.4,22.0,abilene-christian,2014
1,2014-01-11,southeastern-louisiana,0,-4.12,season2014,6.0,0.400000,90.0,59.0,0.5052,...,0.7640,11.6,40.2,20.4,8.8,3.8,12.0,18.2,abilene-christian,2014
2,2014-01-16,oral-roberts,0,-4.12,season2014,6.0,0.375000,86.8,65.4,0.4646,...,0.8012,11.2,40.2,17.8,7.2,2.6,10.8,19.0,abilene-christian,2014
3,2014-01-18,central-arkansas,1,-4.12,season2014,6.0,0.352941,80.6,69.2,0.4454,...,0.8170,10.8,37.0,14.4,6.8,1.4,11.0,19.6,abilene-christian,2014
4,2014-01-23,lamar,0,-4.12,season2014,7.0,0.388889,77.8,75.0,0.4444,...,0.7930,8.8,33.4,13.6,7.4,1.4,11.8,20.8,abilene-christian,2014

In [7]:
clusters.head()

,Team,Season,C0,C1,C2,F0,F1,F2,G0,G1,G2,G3
0,abilene-christian,2014,0,0,0,0.0930677,0.145657,0.160319,0.175299,0,0.102311,0.323347
1,abilene-christian,2015,0,0,0,0.0848387,0.145484,0.111129,0.166613,0,0.107742,0.384194
2,abilene-christian,2016,0,0,0,0,0.132,0.26272,0.3616,0,0.0968,0.14688
3,abilene-christian,2017,0.0954237,0,0,0,0.07,0.0764407,0.277458,0,0.340508,0.140169
4,abilene-christian,2018,0.110698,0,0.0162791,0,0.0465116,0.0505426,0.323411,0,0.451318,0.00124031

In [8]:
experience.head()

                Team Season exp_factor
0  abilene-christian   2014    2.18072
1  abilene-christian   2015    2.76839
2  abilene-christian   2016     2.6672
3  abilene-christian   2017    2.15559
4  abilene-christian   2018    2.97798

In [9]:
gamelogs.GameType.value_counts()

season2017     6489
season2018     6470
season2016     6469
season2015     6427
season2014     6420
tourney2015     173
tourney2016     168
tourney2014     162
tourney2017     153
tourney2018     115
Name: GameType, dtype: int64

In [10]:
def season(row):
    row['Season'] = row['GameType'][-4:]
    return row

In [11]:
gamelogs = gamelogs.apply(season, axis=1)

In [12]:
gamelogs.head()

,Date,Opp,W,sos,GameType,Ws,Wp,ppg,pApg,FGp,...,FTp,ORBpg,RBpg,ASTpg,STLpg,BLKpg,TOpg,PFpg,Tm,Season
0,2014-01-09,new-orleans,0,-4.12,season2014,2.0,0.200000,63.8,68.8,0.3938,...,0.7078,7.8,27.4,12.2,7.2,2.8,13.4,22.0,abilene-christian,2014
1,2014-01-11,southeastern-louisiana,0,-4.12,season2014,6.0,0.400000,90.0,59.0,0.5052,...,0.7640,11.6,40.2,20.4,8.8,3.8,12.0,18.2,abilene-christian,2014
2,2014-01-16,oral-roberts,0,-4.12,season2014,6.0,0.375000,86.8,65.4,0.4646,...,0.8012,11.2,40.2,17.8,7.2,2.6,10.8,19.0,abilene-christian,2014
3,2014-01-18,central-arkansas,1,-4.12,season2014,6.0,0.352941,80.6,69.2,0.4454,...,0.8170,10.8,37.0,14.4,6.8,1.4,11.0,19.6,abilene-christian,2014
4,2014-01-23,lamar,0,-4.12,season2014,7.0,0.388889,77.8,75.0,0.4444,...,0.7930,8.8,33.4,13.6,7.4,1.4,11.8,20.8,abilene-christian,2014

In [24]:
gamelogs = gamelogs.apply(ID, axis=1)
clusters = clusters.apply(ID, axis=1)
experience = experience.apply(ID, axis=1)