In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import date
import time
import pickle

In [2]:
def school_name_transform(school_name):
    school_name = school_name.lower()
    school_name = school_name.replace(" & ", " ")
    school_name = school_name.replace("&", "")
    school_name = school_name.replace("ncaa", "")
    school_name = school_name.strip()
    school_name = school_name.replace(" ", "-")
    school_name = school_name.replace("(", "")
    school_name = school_name.replace(")", "")
    school_name = school_name.replace(".", "")
    school_name = school_name.replace("'", "")
    
    if school_name == 'siu-edwardsville':
        school_name = 'southern-illinois-edwardsville'
    elif school_name == 'vmi':
        school_name = 'virginia-military-institute'
    elif school_name == 'uc-davis':
        school_name = 'california-davis'
    elif school_name == 'uc-irvine':
        school_name = 'california-irvine'
    elif school_name == 'uc-riverside':
        school_name = 'california-riverside'
    elif school_name == 'uc-santa-barbara':
        school_name = 'california-santa-barbara'
    
    return school_name

In [8]:
def sos_csv_creator(seasons):
    '''
    Inputs:
        team = team (formatted as in url)
        season = season year

    Output: DataFrame of all games
    '''
    sos_df = pd.DataFrame()

    for season in seasons:

        url = 'https://www.sports-reference.com/cbb/seasons/{}-school-stats.html#basic_school_stats::none'.format(season)

        '''Read season school stats'''
        df = pd.read_html(url)[0]

        '''Transform'''

        '''Remove double Headers'''
        dub_header = df.columns.tolist()
        cols = [col[1].lower() for col in dub_header]
        df.columns = cols

        '''Pick needed columns'''
        df = df[['school', 'sos']]

        '''Add school-format column'''
        df['school-format'] = df['school']

        '''Add season column'''
        df['season'] = season

        '''Update School Names'''
        df['school-format'] = df['school-format'].apply(school_name_transform)

        '''Remove divider rows'''
        df = df[df['school'] != 'Overall'] 
        df = df[df['school'] != 'School']
        df.reset_index(inplace=True, level=None)
        df = df.drop(['index'], axis=1)

        '''Transform to dict'''
        df.to_csv('../sos/sos_list{}.csv'.format(season))

        time.sleep(15)

In [9]:
df = sos_csv_creator([2018])

In [10]:
df = pd.read_csv('../sos/sos_list2018.csv', index_col=0)

In [11]:
df.head(30)

                  school    sos         school-format  season
0      Abilene Christian  -6.82     abilene-christian    2018
1              Air Force   1.72             air-force    2018
2                  Akron  -1.92                 akron    2018
3            Alabama A&M  -8.04            alabama-am    2018
4     Alabama-Birmingham  -0.65    alabama-birmingham    2018
5          Alabama State  -8.62         alabama-state    2018
6           Alabama NCAA  10.64               alabama    2018
7            Albany (NY)  -5.41             albany-ny    2018
8           Alcorn State  -8.60          alcorn-state    2018
9               American  -6.17              american    2018
10     Appalachian State  -2.65     appalachian-state    2018
11    Arizona State NCAA   6.56         arizona-state    2018
12          Arizona NCAA   6.84               arizona    2018
13  Arkansas-Little Rock  -2.21  arkansas-little-rock    2018
14   Arkansas-Pine Bluff  -9.36   arkansas-pine-bluff    2018
15        Arkansas State  -3.02        arkansas-state    2018
16         Arkansas NCAA   9.85              arkansas    2018
17                  Army  -7.17                  army    2018
18           Auburn NCAA   7.29                auburn    2018
19           Austin Peay  -2.49           austin-peay    2018
20            Ball State  -1.99            ball-state    2018
21                Baylor   9.17                baylor    2018
22               Belmont  -2.88               belmont    2018
23       Bethune-Cookman -12.48       bethune-cookman    2018
24            Binghamton  -6.36            binghamton    2018
25           Boise State   3.05           boise-state    2018
26        Boston College   7.20        boston-college    2018
27     Boston University  -5.84     boston-university    2018
28   Bowling Green State  -2.88   bowling-green-state    2018
29               Bradley   0.36               bradley    2018