In [1]:
import pandas as pd
import numpy as np

In [2]:
msuurl = 'https://www.sports-reference.com/cbb/schools/michigan-state/2018-gamelogs.html#sgl-basic::none'

In [3]:
df = pd.read_html(msuurl)[0]

In [4]:
df = df.iloc[:, 0:23]
df = df.drop(df.index[[20,21]])

In [5]:
# df.columns

In [5]:
dubcols = df.columns.tolist()

In [6]:
cols = [col[1] for col in dubcols]

In [7]:
cols

['G',
 'Date',
 '\xa0',
 'Opp',
 'W/L',
 'Tm',
 'Opp',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF']

In [8]:
df.columns = cols

In [10]:
df

,G,Date,,Opp,W/L,Tm,Opp,FG,FGA,FG%,...,FT,FTA,FT%,ORB,TRB,AST,STL,BLK,TOV,PF
0,1,2017-11-10,NaN,North Florida,W,98,66,35,61,.574,...,25,32,.781,13,45,22,12,10,21,21
1,2,2017-11-14,N,Duke,L,81,88,31,61,.508,...,10,18,.556,8,30,25,1,12,17,21
2,3,2017-11-19,NaN,Stony Brook,W,93,71,33,57,.579,...,22,27,.815,11,40,20,5,7,14,20
3,4,2017-11-23,N,DePaul,W,73,51,25,53,.472,...,13,17,.765,8,37,17,5,1,14,26
4,5,2017-11-25,N,UConn,W,77,57,32,66,.485,...,5,10,.500,11,38,12,3,4,8,16
5,6,2017-11-26,N,UNC,W,63,45,22,55,.400,...,9,13,.692,10,44,16,7,7,22,23
6,7,2017-11-30,NaN,Notre Dame,W,81,63,31,60,.517,...,10,14,.714,13,39,21,4,6,13,14
7,8,2017-12-03,NaN,Nebraska,W,86,57,27,57,.474,...,27,36,.750,11,45,16,1,11,6,16
8,9,2017-12-05,@,Rutgers,W,62,52,22,57,.386,...,10,16,.625,12,40,15,4,13,14,17
9,10,2017-12-09,NaN,Southern Utah,W,88,63,28,59,.475,...,23,31,.742,14,48,24,6,12,11,12
10,11,2017-12-16,N,Oakland,W,86,73,31,60,.517,...,15,23,.652,14,43,18,7,6,17,16
11,12,2017-12-18,NaN,Houston Baptist,W,107,62,36,56,.643,...,25,33,.758,10,42,30,4,16,14,22
12,13,2017-12-21,NaN,Long Beach State,W,102,60,39,64,.609,...,11,13,.846,12,35,28,9,10,11,15
13,14,2017-12-29,NaN,Cleveland State,W,111,61,41,63,.651,...,14,18,.778,15,47,29,1,4,11,18
14,15,2017-12-31,NaN,Savannah State,W,108,52,44,70,.629,...,12,22,.545,14,57,35,6,7,17,14
15,16,2018-01-04,NaN,Maryland,W,91,61,32,56,.571,...,11,15,.733,7,33,30,4,9,7,17
16,17,2018-01-07,@,Ohio State,L,64,80,23,59,.390,...,11,13,.846,9,33,13,3,1,11,17
17,18,2018-01-10,NaN,Rutgers,W (1 OT),76,72,21,51,.412,...,25,34,.735,7,36,19,3,8,13,19
18,19,2018-01-13,NaN,Michigan,L,72,82,21,46,.457,...,27,32,.844,8,32,13,3,8,17,26
19,20,2018-01-19,NaN,Indiana,W,85,57,32,59,.542,...,11,17,.647,11,44,23,2,7,13,14
22,21,2018-01-22,@,Illinois,W,87,74,30,44,.682,...,23,28,.821,9,37,15,5,9,25,18
23,22,2018-01-26,NaN,Wisconsin,W,76,61,27,54,.500,...,14,16,.875,9,34,19,2,9,12,19
24,23,2018-01-28,@,Maryland,W,74,68,25,63,.397,...,19,23,.826,16,40,11,6,7,9,19
25,24,2018-01-31,NaN,Penn State,W,76,68,24,48,.500,...,20,25,.800,4,38,18,5,7,15,14
26,25,2018-02-03,@,Indiana,W,63,60,23,47,.489,...,8,17,.471,3,26,15,3,13,11,24
27,26,2018-02-06,@,Iowa,W,96,93,32,57,.561,...,24,29,.828,6,31,20,3,4,10,19
28,27,2018-02-10,NaN,Purdue,W,68,65,29,60,.483,...,4,6,.667,6,37,21,2,4,6,14
29,28,2018-02-13,@,Minnesota,W,87,57,32,60,.533,...,9,14,.643,12,46,27,3,4,13,14
30,29,2018-02-17,@,Northwestern,W,65,60,20,46,.435,...,17,21,.810,6,31,16,3,0,11,16
31,30,2018-02-20,NaN,Illinois,W,81,61,24,51,.471,...,22,26,.846,7,40,20,2,11,8,20
32,31,2018-02-25,@,Wisconsin,W,68,63,23,53,.434,...,14,18,.778,13,38,10,4,8,12,18
33,32,2018-03-02,N,Wisconsin,W,63,60,24,56,.429,...,10,11,.909,11,36,10,3,7,10,14
34,33,2018-03-03,N,Michigan,L,64,75,24,63,.381,...,9,10,.900,9,32,10,4,1,8,23

In [11]:
# df.columns

In [12]:
newcols = ['G', 'Date', 'Blank', 'Opp', 'W', 'Pts', 'PtsA', 'FG', 'FGA', 
           'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'RB', 
           'AST', 'STL', 'BLK', 'TO', 'PF']

In [13]:
df.columns = newcols

In [14]:
df['W'] = df['W'].astype(str).str[0]

In [15]:
df['W'] = df['W'].map({'W': 1, 'L': 0})

In [23]:
df['Opp'] = df['Opp'].str.lower()
df['Opp'] = df['Opp'].str.replace("[^\w\s\n.']",'')
df['Opp'] = df['Opp'].str.replace("",'-')

In [17]:
df.columns

Index(['G', 'Date', 'Blank', 'Opp', 'W', 'Pts', 'PtsA', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'RB', 'AST', 'STL',
       'BLK', 'TO', 'PF'],
      dtype='object')

In [18]:
df['Ws'] = df['W'].cumsum(axis=0)
df['Wp'] = df['Ws'].astype(int) / df['G'].astype(int)
df['ppg'] = df['Pts'].rolling(window=5,center=False).mean()
df['pApg'] = df['PtsA'].rolling(window=5,center=False).mean()
df['FGp'] = df['FG%'].rolling(window=5,center=False).mean()
df['3Pg'] = df['3P%'].rolling(window=5,center=False).mean()
df['FTp'] = df['FT%'].rolling(window=5,center=False).mean()
df['ORBpg'] = df['ORB'].rolling(window=5,center=False).mean()
df['RBpg'] = df['RB'].rolling(window=5,center=False).mean()
df['ASTpg'] = df['AST'].rolling(window=5,center=False).mean()
df['STLpg'] = df['STL'].rolling(window=5,center=False).mean()
df['BLKpg'] = df['BLK'].rolling(window=5,center=False).mean()
df['TOpg'] = df['TO'].rolling(window=5,center=False).mean()
df['PFpg'] = df['PF'].rolling(window=5,center=False).mean()

In [19]:
# df.columns

In [20]:
df = df.drop(['G', 'Blank', 'Pts', 'PtsA', 'FG', 'FGA', 'FG%',
              '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'RB', 
              'AST', 'STL', 'BLK', 'TO', 'PF'], axis=1)

In [21]:
df = df.dropna()

In [22]:
df

,Date,Opp,W,Ws,Wp,ppg,pApg,FGp,3Pg,FTp,ORBpg,RBpg,ASTpg,STLpg,BLKpg,TOpg,PFpg
4,2017-11-25,uconn,1,4,0.800000,84.4,66.6,0.5236,0.3644,0.6834,10.2,38.0,19.2,5.2,6.8,14.8,20.8
5,2017-11-26,unc,1,5,0.833333,77.4,62.4,0.4888,0.3914,0.6656,9.6,37.8,18.0,4.2,6.2,15.0,21.2
6,2017-11-30,notre dame,1,6,0.857143,77.4,57.4,0.4906,0.4052,0.6972,10.6,39.6,17.2,4.8,5.0,14.2,19.8
7,2017-12-03,nebraska,1,7,0.875000,76.0,54.6,0.4696,0.3912,0.6842,10.6,40.6,16.4,4.0,5.8,12.6,19.0
8,2017-12-05,rutgers,1,8,0.888889,73.8,54.8,0.4524,0.3804,0.6562,11.4,41.2,16.0,3.8,8.2,12.6,17.2
9,2017-12-09,southern utah,1,9,0.900000,76.0,56.0,0.4504,0.3864,0.7046,12.0,43.2,18.4,4.4,9.8,13.2,16.4
10,2017-12-16,oakland,1,10,0.909091,80.6,61.6,0.4738,0.3876,0.6966,12.8,43.0,18.8,4.4,9.6,12.2,15.0
11,2017-12-18,houston baptist,1,11,0.916667,85.8,61.4,0.4990,0.4018,0.7054,12.2,43.6,20.6,4.4,11.6,12.4,16.6
12,2017-12-21,long beach state,1,12,0.923077,89.0,62.0,0.5260,0.4388,0.7246,12.4,41.6,23.0,6.0,11.4,13.4,16.4
13,2017-12-29,cleveland state,1,13,0.928571,98.8,63.8,0.5790,0.4780,0.7552,13.0,43.0,25.8,5.4,9.6,12.8,16.6
14,2017-12-31,savannah state,1,14,0.933333,102.8,61.6,0.6098,0.4560,0.7158,13.0,44.8,28.0,5.4,8.6,14.0,17.0
15,2018-01-04,maryland,1,15,0.937500,103.8,59.2,0.6206,0.4920,0.7320,11.6,42.8,30.4,4.8,9.2,12.0,17.2
16,2018-01-07,ohio state,0,15,0.882353,95.2,62.8,0.5700,0.4480,0.7496,11.4,41.0,27.0,4.6,6.2,11.4,16.2
17,2018-01-10,rutgers,1,16,0.888889,90.0,65.2,0.5306,0.4532,0.7274,10.4,41.2,25.2,3.4,5.8,11.8,17.0
18,2018-01-13,michigan,0,16,0.842105,82.2,69.4,0.4918,0.3840,0.7406,9.0,38.2,22.0,3.8,6.6,13.0,18.6
19,2018-01-19,indiana,1,17,0.850000,77.6,70.4,0.4744,0.4112,0.7610,8.4,35.6,19.6,3.0,6.6,12.2,18.6
22,2018-01-22,illinois,1,18,0.857143,76.8,73.0,0.4966,0.3858,0.7786,8.8,36.4,16.6,3.2,6.6,15.8,18.8
23,2018-01-26,wisconsin,1,19,0.863636,79.2,69.2,0.5186,0.4140,0.7844,8.8,36.6,17.8,3.0,8.2,16.0,19.2
24,2018-01-28,maryland,1,20,0.869565,78.8,68.4,0.5156,0.3668,0.8026,10.6,37.4,16.2,3.6,8.0,15.2,19.2
25,2018-01-31,penn state,1,21,0.875000,79.6,65.6,0.5242,0.4148,0.7938,9.8,38.6,17.2,4.0,7.8,14.8,16.8
26,2018-02-03,indiana,1,22,0.880000,75.2,66.2,0.5136,0.4148,0.7586,8.2,35.0,15.6,4.2,9.0,14.4,18.8
27,2018-02-06,iowa,1,23,0.884615,77.0,70.0,0.4894,0.4202,0.7600,7.6,33.8,16.6,3.8,8.0,11.4,19.0
28,2018-02-10,purdue,1,24,0.888889,75.4,70.8,0.4860,0.4026,0.7184,7.0,34.4,17.0,3.8,7.0,10.2,18.0
29,2018-02-13,minnesota,1,25,0.892857,78.0,68.6,0.5132,0.4822,0.6818,6.2,35.6,20.2,3.2,6.4,11.0,17.0
30,2018-02-17,northwestern,1,26,0.896552,75.8,67.0,0.5002,0.4768,0.6838,6.6,34.2,19.8,2.8,5.0,10.2,17.4
31,2018-02-20,illinois,1,27,0.900000,79.4,67.2,0.4966,0.4582,0.7588,7.4,37.0,20.8,2.6,4.6,9.6,16.6
32,2018-02-25,wisconsin,1,28,0.903226,73.8,61.2,0.4712,0.4440,0.7488,8.8,38.4,18.8,2.8,5.4,10.0,16.4
33,2018-03-02,wisconsin,1,29,0.906250,72.8,60.2,0.4604,0.4400,0.7972,9.8,38.2,16.6,3.0,6.0,10.8,16.4
34,2018-03-03,michigan,0,29,0.878788,68.2,63.8,0.4300,0.3688,0.8486,9.2,35.4,13.2,3.2,5.4,9.8,18.2