In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('/Users/sec/galvanize/capstones/capstone-1/2017-2018_gamedata.csv', index_col=0)

In [21]:
cols = df.columns.tolist()
cols = [col.lower() for col in cols]
df.columns = cols

In [22]:
df.columns

Index(['3pm-a', 'a', 'blk', 'date', 'def', 'fgm-a', 'ftm-a', 'match', 'min',
       'off', 'pf', 'player', 'pts', 'stl', 'team', 'to', 'tot'],
      dtype='object')

In [25]:
df.describe().round(2)

,a,blk,def,off,pf,pts,stl,to,tot
count,109191.00,109191.00,109191.00,109191.00,109191.00,109191.00,109191.00,109191.00,109191.00
mean,1.37,0.34,2.37,0.87,1.81,7.39,0.62,1.26,3.25
std,1.81,0.76,2.29,1.24,1.43,6.96,0.93,1.36,2.97
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,0.00,1.00,0.00,1.00,2.00,0.00,0.00,1.00
50%,1.00,0.00,2.00,0.00,2.00,6.00,0.00,1.00,3.00
75%,2.00,0.00,4.00,1.00,3.00,12.00,1.00,2.00,5.00
max,22.00,11.00,19.00,12.00,6.00,52.00,9.00,12.00,24.00

In [26]:
df.head()

,3pm-a,a,blk,date,def,fgm-a,ftm-a,match,min,off,pf,player,pts,stl,team,to,tot
0,1-2,2.0,1.0,2017-11-10,2.0,1-2,0-0,Savannah State\n vs. Cincinnati\n,22:00,0.0,0.0,Javaris Jenkins,3.0,0.0,Savannah State\n,2.0,2.0
1,0-3,1.0,0.0,2017-11-10,3.0,6-12,1-2,Savannah State\n vs. Cincinnati\n,20:00,2.0,3.0,Jahlin Smith,13.0,1.0,Savannah State\n,4.0,5.0
2,1-9,5.0,0.0,2017-11-10,3.0,3-14,4-6,Savannah State\n vs. Cincinnati\n,30:00,1.0,2.0,Ty'Lik Evans,11.0,3.0,Savannah State\n,2.0,4.0
3,1-4,2.0,0.0,2017-11-10,2.0,3-11,4-5,Savannah State\n vs. Cincinnati\n,25:00,1.0,2.0,Dexter McClanahan,11.0,2.0,Savannah State\n,2.0,3.0
4,4-7,6.0,0.0,2017-11-10,5.0,5-9,0-0,Savannah State\n vs. Cincinnati\n,26:00,0.0,4.0,Austin Dasent,14.0,3.0,Savannah State\n,5.0,5.0

Data Cleaning:
- Split 3pm-a, fgm-a, ftm-a to pm, a,
- remove mins, and date, player
- cols? def, off, pf
- group by team
- add win, loss, and win % (Where to get this data?)
- games played
- all stats on per game basis
    - or per 100 posessions (Where to get this data?)
- add percent for 3p, fg, ft
- Pick a winner model
- pick a seed model

Other:
    - remove match?
    - could i categorize teams somehow?  Strength somehow?
        - off stregth score
        - def strength score
        - number os posessions