In [1]:
import pandas as pd
import numpy as np

%run msu.py

In [2]:
# games

In [3]:
games['count'] = games.groupby('ID').cumcount() + 1

In [4]:
# games

In [5]:
games1 = games[games['count'] == 1]
games2 = games[games['count'] == 2]

In [6]:
games2

,Date,Opp,W,Ws,Wp,ppg,pApg,FGp,3Pp,FTp,...,ASTpg,STLpg,BLKpg,TOpg,PFpg,Tm,sos,matchup,ID,count
37,2018-02-11,michigan,0,11,0.407407,65.6,70.8,0.4396,0.3794,0.694,...,13.0,3.8,4.0,9.8,19.4,wisconsin,7.67,"michigan,wisconsin","michigan,wisconsin,2018-02-11",2

In [7]:
games2_stats = games2.iloc[:, 5:19] 
games2_id = games2['ID']

In [8]:
g2cols = games2_stats.columns.tolist()

In [9]:
OPcols = ['OP{}'.format(col) for col in g2cols]

In [10]:
games2_stats.columns = OPcols

In [11]:
games2_stats

,OPppg,OPpApg,OPFGp,OP3Pp,OPFTp,OPORBpg,OPRBpg,OPASTpg,OPSTLpg,OPBLKpg,OPTOpg,OPPFpg,OPTm,OPsos
37,65.6,70.8,0.4396,0.3794,0.694,7.6,26.6,13.0,3.8,4.0,9.8,19.4,wisconsin,7.67

In [13]:
games2 = pd.concat([games2_stats, games2_id], axis=1)

In [14]:
games2

,OPppg,OPpApg,OPFGp,OP3Pp,OPFTp,OPORBpg,OPRBpg,OPASTpg,OPSTLpg,OPBLKpg,OPTOpg,OPPFpg,OPTm,OPsos,ID
37,65.6,70.8,0.4396,0.3794,0.694,7.6,26.6,13.0,3.8,4.0,9.8,19.4,wisconsin,7.67,"michigan,wisconsin,2018-02-11"

In [17]:
games.head()

,Date,Opp,W,Ws,Wp,ppg,pApg,FGp,3Pp,FTp,...,OPORBpg,OPRBpg,OPASTpg,OPSTLpg,OPBLKpg,OPTOpg,OPPFpg,OPTm,OPsos,ID
ID,,,,,,,,,,,,,,,,,,,,,
"michigan,virginia-commonwealth,2017-11-22",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"california-riverside,michigan,2017-11-26",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,north-carolina,2017-11-29",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"indiana,michigan,2017-12-02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,ucla,2017-12-09",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
games1.head()

,Date,Opp,W,Ws,Wp,ppg,pApg,FGp,3Pp,FTp,...,ASTpg,STLpg,BLKpg,TOpg,PFpg,Tm,sos,matchup,ID,count
0,2017-11-22,virginia-commonwealth,1,5,0.833333,75.6,62.6,0.5018,0.3378,0.7276,...,14.2,6.2,3.4,7.6,13.4,michigan,7.64,"michigan,virginia-commonwealth","michigan,virginia-commonwealth,2017-11-22",1
1,2017-11-26,california-riverside,1,6,0.857143,78.6,58.0,0.5216,0.3718,0.6700,...,16.2,7.2,4.2,9.0,12.4,michigan,7.64,"california-riverside,michigan","california-riverside,michigan,2017-11-26",1
2,2017-11-29,north-carolina,0,6,0.750000,80.6,65.8,0.5086,0.3610,0.6054,...,16.8,7.8,4.8,9.2,13.6,michigan,7.64,"michigan,north-carolina","michigan,north-carolina,2017-11-29",1
3,2017-12-02,indiana,1,7,0.777778,79.4,61.4,0.5116,0.3798,0.5826,...,17.6,7.6,5.2,9.8,12.6,michigan,7.64,"indiana,michigan","indiana,michigan,2017-12-02",1
4,2017-12-09,ucla,1,8,0.727273,73.4,64.6,0.4558,0.3488,0.5356,...,16.8,8.0,3.2,10.0,15.0,michigan,7.64,"michigan,ucla","michigan,ucla,2017-12-09",1

In [19]:
games2.head()

,OPppg,OPpApg,OPFGp,OP3Pp,OPFTp,OPORBpg,OPRBpg,OPASTpg,OPSTLpg,OPBLKpg,OPTOpg,OPPFpg,OPTm,OPsos,ID
37,65.6,70.8,0.4396,0.3794,0.694,7.6,26.6,13.0,3.8,4.0,9.8,19.4,wisconsin,7.67,"michigan,wisconsin,2018-02-11"

In [15]:
games = pd.concat([games1, games2], axis=1, join_axes=[games.ID])

In [16]:
games

,Date,Opp,W,Ws,Wp,ppg,pApg,FGp,3Pp,FTp,...,OPORBpg,OPRBpg,OPASTpg,OPSTLpg,OPBLKpg,OPTOpg,OPPFpg,OPTm,OPsos,ID
ID,,,,,,,,,,,,,,,,,,,,,
"michigan,virginia-commonwealth,2017-11-22",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"california-riverside,michigan,2017-11-26",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,north-carolina,2017-11-29",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"indiana,michigan,2017-12-02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,ucla,2017-12-09",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,texas,2017-12-12",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"jacksonville,michigan,2017-12-30",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"iowa,michigan,2018-01-02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"illinois,michigan,2018-01-06",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,purdue,2018-01-09",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"maryland,michigan,2018-01-15",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,nebraska,2018-01-18",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,purdue,2018-01-25",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,northwestern,2018-01-29",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,minnesota,2018-02-03",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,northwestern,2018-02-06",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,wisconsin,2018-02-11",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"iowa,michigan,2018-02-14",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"maryland,michigan,2018-02-24",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"iowa,michigan,2018-03-01",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,nebraska,2018-03-02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,purdue,2018-03-04",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"ucla,wisconsin,2017-11-21",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"milwaukee,wisconsin,2017-11-24",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"virginia,wisconsin,2017-11-27",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"temple,wisconsin,2017-12-06",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"marquette,wisconsin,2017-12-09",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"massachusetts-lowell,wisconsin,2017-12-30",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"indiana,wisconsin,2018-01-02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"nebraska,wisconsin,2018-01-09",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"purdue,wisconsin,2018-01-16",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"illinois,wisconsin,2018-01-19",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"iowa,wisconsin,2018-01-23",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"nebraska,wisconsin,2018-01-29",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"northwestern,wisconsin,2018-02-01",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"maryland,wisconsin,2018-02-04",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"illinois,wisconsin,2018-02-08",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"michigan,wisconsin,2018-02-11",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"purdue,wisconsin,2018-02-15",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"minnesota,wisconsin,2018-02-19",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"northwestern,wisconsin,2018-02-22",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"maryland,wisconsin,2018-03-01",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN